### ISSUE TITLE
Have you ever tried to run your code?

### ISSUE THREAD

**Issue by mi2shiii** [ihuaylupo/manning-smia#18]
I'm trying to clean this mess up in your code, but I couldn't!
Have you honestly at least one time tried to run your code? Nothing is runnable.
all docker-compose files stuck in loads of exceptions!
No offence, but you should be responsible with what you are sharing. your book is quite good, but the code is a real mess.
We cannot understand anything when we can not run the code.

**Comment by ihuaylupo** [comment]
@mi2shiii Sorry for the late reply. Are you still having problems? Everything should run. Please email me directly to solve the problems you are having.

Sorry for the inconvenience.
