### ISSUE TITLE
Chapter 4 build fails apk not found.

### ISSUE THREAD

**Issue by ezazpi** [ihuaylupo/manning-smia#4]
When running the `mvn` package `dockerfile:build` command with the second (staged) dockerfile example, the apk command is not recognized:

`[ERROR]` The command '/bin/sh -c apk update && apk upgrade && apk add netcat-openbsd' returned a non-zero code: `127`

I changed the stage 2 `FROM openjdk:14-slim` to `FROM alpine:3.4` to get a clean build (see attached).

I am running Maven under Windows 10.

[dockerfile.txt](https://github.com/ihuaylupo/manning-smia/files/5179925/dockerfile.txt)

**Comment by ihuaylupo** [comment]
I will take a look at it. But If that's the case we should remove the run apk from the dockerfile. (I'm not taking advantage of the benefits of that apk so it's safe to remove it) Changing the base image to 14 is not a good idea because you will be using Java 14 instead of 11.

**Comment by ezazpi** [comment]
Thank you.  I switched to 11, but still encountered the apk error (updated pom.xml to 11 and dockerfile's FROM entries to openjdk:11-slim).  From your output, I know you did not encounter the apk error so I'm not sure if this is unique to me.  I also tried apt-get, but had the same errors.

FROM alpine:3.4 is only to handle the apk entry, I returned to using FROM openjdk:14-slim just before the ARG DEPENDENCY line.  This ensures LicenseServiceApplication will be found in the classpath and so that Java can be found.  That attached file contains the dockerfile details.  The dockerfile build is successful, as was the docker run command.  As you mentioned, if netcat-openbsd is not being used, it's probably better to not include it and save on download time.

[dockerfile.txt](https://github.com/ihuaylupo/manning-smia/files/5180015/dockerfile.txt)

**Comment by ihuaylupo** [comment]
Hi, you can also use the dockerfile located in the chapter14 folder. I just ran the command `mvn clean package dockerfile:build` and is working.

Thanks for letting me know. I will be updating the content of the chapter to remove the apk line from the code listings.
