### ISSUE TITLE
Chapter 5 - Unable to find the licenses table.

### ISSUE THREAD

**Issue by ezazpi** [ihuaylupo/manning-smia#6]
When running, for example, `http://localhost:8080/v1/organization/optimaGrowth/license/0235431845` from Postman, I get the following exception:

Caused by: org.postgresql.util.PSQLException: ERROR: relation "licenses" does not exist

Here's the query:

licensingservice_1  | Hibernate: select license0_.license_id as license_1_0_, license0_.comment as comment2_0_, license0_.description as descript3_0_, license0_.license_type as license_4_0_, license0_.organization_id as organiza5_0_, license0_.product_name as product_6_0_ from licenses license0_ where license0_.organization_id=? and license0_.license_id=?
database_1          | 2020-09-08 00:21:48.506 UTC [46] ERROR:  relation "licenses" does not exist at character 246
database_1          | 2020-09-08 00:21:48.506 UTC [46] STATEMENT:  select license0_.license_id as license_1_0_, license0_.comment as comment2_0_, license0_.description as descript3_0_, license0_.license_type as license_4_0_, license0_.organization_id as organiza5_0_, license0_.product_name as product_6_0_ from licenses license0_ where license0_.organization_id=$1 and license0_.license_id=$2

I did a `mvn clean` before the `docker-compose up.`  Do the queries need to reference `public.licenses` as is used in `chapter5\docker\database.sql`?

**Comment by ihuaylupo** [comment]
Please verify that the organization and license tables are created in the PostgreSQL database. In order to use the services you have to create the database tables, you can find the script in the docker's folder.

**Comment by ezazpi** [comment]
I added a more detailed comment for a similar issue I had with the organizations table in chapter 8.  In short, the following changes were required to the database.sql script.  

LC_COLLATE = 'en_US.UTF-8' <- change to 'en_US.utf8'
LC_CTYPE = 'en_US.UTF-8' <- change to 'en_US.utf8'

The 'en_US.UTF-8' values seem to be incompatible with the template in the postgresql Docker image.  Changing to 'en_US.utf8' for both entries allowed the script to successfully complete.  Thank you.
