### ISSUE TITLE
Chapter 6 eureka-server.yml error.

### ISSUE THREAD

**Issue by ezazpi** [ihuaylupo/manning-smia#7]
`C:\Users\ezazpi\Documents\IntelliJ\eurekaserver\src\main\resources\config>docker-compose -f eureka-server.yml up`
ERROR: Invalid interpolation format for "client" option in service "eureka": "http://${eureka.instance.hostname}:${server.port}/eureka/"

Please see the attached.  I am using eureka-server.yml as described in the book, which is different from the GitHub version.  Still, I tried docker-compose with the GitHub version and it also failed:

`C:\Users\ezazpi\Documents\IntelliJ\manning-smia\chapter6\Final\eurekaserver\src\main\resources>docker-compose -f bootstrap.yml up`
ERROR: The Compose file '.\bootstrap.yml' is invalid because:
Unsupported config option for spring: 'cloud'

[eureka-server.yml.txt](https://github.com/ihuaylupo/manning-smia/files/5185695/eureka-server.yml.txt)

**Comment by ihuaylupo** [comment]
If you want to run the docker-compose command, you need to make sure you are on the root folder of the project and then execute the following command. `docker-compose -f docker/docker-compose.yml up`.

The commands you are running  `docker-compose -f eureka-server.yml up` and `docker-compose -f bootstrap.yml up` are invalid. To start all the container services, you need to execute the following docker-compose command on the root folder `docker-compose -f docker/docker-compose.yml up`.

**Comment by ezazpi** [comment]
Thank you.  Yes, I was running this incorrectly when I reported my issue.  I was running it properly since Thursday without issue.  When I reported this problem, I was under the impression I had to bring up each service individually.  Wednesday or Thursday I realized you made it easy on us with the docker/docker-compose.yml file.
