### ISSUE TITLE
Chapter 7 Figure 7.7 Behavior not as documented.

### ISSUE THREAD

**Issue by ezazpi** [ihuaylupo/manning-smia#9]
I'm using the cloned chapter 7 code.  I updated pom.xml with the documented Resilience4j property and dependencies.  I made no changes to LicenseService.java as it already contained the @CircuitBreaker annotation and the Listing 7.3 randomlyRunLong and sleep methods.  I also did not remove the @RateLimiter, @Retry, and @Bulkhead annotations and corresponding fallBackMethods.  My guess is the @CircuitBreaker fallBackMethod parameter is likely causing my result to differ from the book's.

After cleaning and starting the services, I attempted, http://localhost:8080/v1/organization/e6a625cc-718b-48c2-ac76-1dfdff9a531e/license/.  I tried over 12 times but could never get the results described in Listing 7.7 or the text above Listing 7.7.  Each time the response was the same:

[
    {
        "licenseId": "0000000-00-00000",
        "organizationId": "e6a625cc-718b-48c2-ac76-1dfdff9a531e",
        "productName": "Sorry no licensing information currently available",
        "links": []
    }
]

I never got the following either immediately or the Figure 7.7 results after the ring bit buffer filled.

{
"timestamp": 1595178498383,
"status": 500,
"error": "Internal Server Error",
"message": "No message available",
"path": "/v1/organization/e6a625cc-718b-48c2-ac76-
1dfdff9a531e/license/"
}

**Comment by ihuaylupo** [comment]
In this case, the issue is that you don't have any record with that ID. Please verify the ID of the organization record you have on the database and then execute http://localhost:8080/v1/organization/${Organization_ID}/license/

**Comment by PetreVane** [comment]
@ezazpi 
if you're throwing an exception when your database record is null, then the circuit breaker will catch that exception and call it's fallback logic. This is because the circuit breaker catches all objects extending Throwable class.  If you are implementing your own exception handling, you could add a small if statement in your fallback logic and check if the catched exception is of type "YourCustomException" and if it is, then throw that exception again. 


        @SuppressWarnings("unused")
        private LicenseDTO getLicenseFallback(String licenseId, Throwable exception) {

              if (exception instanceof MissingLicenseException) {
                    throw new MissingLicenseException("No license found");
               }

            LOGGER.warn("@CircuitBreaker: called 'getLicenseFallback()' method ");
            return new LicenseDTO(NOT_AVAILABLE, FAKE_DATA, FAKE_DATA, FAKE_DATA, FAKE_DATA, FAKE_DATA, FAKE_DATA, FAKE_DATA, FAKE_DATA, FAKE_DATA);
       }
